import React, { Component } from "react";
import Head from "next/head";
import Image from "next/image";
// import { InsightView } from "@gooddata/sdk-ui-ext";
//
// InsightView component depends on document therefore
// it cannot be imported right away, and must be imported
// only after DOM is ready
//
// https://stackoverflow.com/questions/60629258/next-js-document-is-not-defined
// https://stackoverflow.com/questions/51762656/next-js-how-to-dynamically-import-external-client-side-only-react-components-in
import backend from "../backend";

import "@gooddata/sdk-ui-charts/styles/css/main.css";
import "@gooddata/sdk-ui-ext/styles/css/main.css";
import "@gooddata/sdk-ui-filters/styles/css/main.css";
import "@gooddata/sdk-ui-geo/styles/css/main.css";
import "@gooddata/sdk-ui-kit/styles/css/main.css";
import "@gooddata/sdk-ui-pivot/styles/css/main.css";
import "@gooddata/sdk-ui-dashboard/styles/css/main.css";
import styles from "../styles/Home.module.css";

class Home extends Component {
  constructor(props) {
    super(props);

    this.state = {
      // please note that storing components in the state
      // is not the best practice; read more at
      // https://github.com/reduxjs/redux/issues/1248
      DynamicInsightView: () => <p>InsightView component is loading…</p>,
    };
  }

  async componentDidMount() {
    const sdk = await import("@gooddata/sdk-ui-ext");
    this.setState({
      DynamicInsightView: sdk.InsightView,
    });
  }

  render() {
    const { DynamicInsightView } = this.state;

    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div style={{ height: 400, width: 800 }}>
            <DynamicInsightView
              insight="aaxwvA9xaYYu"
              workspace="psk46untnn2vhzs5bokdav3bu2puf6s6" // see WorkspaceProvider in @gooddata/sdk-ui
              backend={backend} // see BackendProvider in @gooddata/sdk-ui
            />
          </div>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
}

export default Home;
